### ISSUE TITLE
gallery crash on exit windows qt59

### ISSUE THREAD

**Issue by uvguy** [QUItCoding/qnanopainter#21] opened 2018-01-14 21:22 UTC
Hello thanks for the superb lib. I noticed that there is something crash as following backtrace on windows at exit 

![1](https://user-images.githubusercontent.com/28796034/34920790-b76ac150-f970-11e7-925c-daccb5441f6b.png)

![2](https://user-images.githubusercontent.com/28796034/34920795-c69d633a-f970-11e7-8744-865b3421ddf3.png)

To reproduce
1. Im using qt59 opengl dynamic 
2. cd where to example gallery source qmake && jom && debug\gallery.exe 
3. Close it

**Comment by QUItCoding** [comment] 2018-01-20 20:41
Looks like also Cellyceos has seen this https://github.com/Cellyceos/qnanopainter/commit/7ea8119772d5727d89c9876101401fec104c849f

But the fix there doesn't seem right, QNanoPainter shouldn't be cleaned up at QNanoQuickItemPainter destructor as QNanoQuickItem (& QNanoQuickItemPainter) may get freed e.g. from delegate when scrolling gallery ListView . And single QNanoPainter is shared among all QNanoQuickItems.

I could not reproduce this, no crash for me with Qt 5.9.3 or Qt 5.10 + msvc2015_64. But looks like some order-of-destruction problem, so pushed a patch which changes how QNanoPainter singleton is managed. Please report if you still get a crash on exit, thanks!

**Comment by uvguy** [comment] 2018-01-21 05:54
My build is 32bit, btw using lastest git still suffering crash at exit.

![3](https://user-images.githubusercontent.com/28796034/35191291-70205cf2-fe6f-11e7-8722-1932291d8039.png)

and

![4](https://user-images.githubusercontent.com/28796034/35191292-7972a3a0-fe6f-11e7-8c77-8f6cc08eb336.png)

**Comment by QUItCoding** [comment] 2018-01-21 13:54
Thanks! I was able to reproduce this now. It happened because when closing the window, OpenGL context had already been gone while NanoVG tries to do GL cleanups. Patch above should fix it, I didn't see crash at exit anymore.

**Comment by uvguy** [comment] 2018-01-21 20:20
confirmed, thanks

**Closed** 2018-01-21 20:20 UTC
